@port = 3000
@host = http://localhost:{{port}}


### Test route A
POST {{host}}/a

###
GET {{host}}/a

###
PUT {{host}}/a

###
PATCH {{host}}/a

###
DELETE {{host}}/a


### Test route B
GET {{host}}/b

### Test route C
GET {{host}}/api/c

### Test route D
GET {{host}}/api/d
