@port = 3000
@host = http://localhost:{{port}}


### Test route A
POST {{host}}/a
Content-Type: application/json

{
    "name": "Sara",
    "surname": "Smith",
    "age": 27
}

###
GET {{host}}/a?page=2&limit=77

###
PUT {{host}}/a

###
PATCH {{host}}/a

###
DELETE {{host}}/a/456


### Test route B
GET {{host}}/b

### Test route C
GET {{host}}/api/c

### Test route D
GET {{host}}/api/d
